---
title: "Lecture 1.3"
date: 2024-01-08
editor_options:
  chunk_output_type: console
---

## Tidy data
```{r}
#..........................load packages.........................
library(tidyverse)
library(janitor)
library(palmerpenguins)

```

```{r}
# untidy data ----
temp_data_wide <- tribble(
  ~date, ~station1, ~station2,  ~station3,
  "2023-10-01", 30.1, 29.8,  31.2, #reminder that numeric includes decimals, while int does not
  "2023-11-01", 28.6, 29.1,  33.4,
  "2023-12-01", 29.9, 28.5,  32.3
)

# make tidy ----
temp_data_long <- temp_data_wide |> 
  pivot_longer(cols = starts_with("station"),
               names_to = "station_id", 
               values_to = "temp_c")
```

Initial wrangling steps:
> View(penguins)
> str(penguins)
> unique(penguins$species)
> length(unique(penguins$species))

## Plot 1
```{r}
ggplot(data = penguins, #ggplot lets you drop the data and mapping arguments
       mapping = aes(x = bill_length_mm,
                     y = bill_depth_mm)) +
  geom_point()

#piping into a ggplot ----
# penguins |>
#   ggplot(aes(x = bill_length_mm, y = bill_length_mm))

```
